[[Zstd]]
arch = "aarch64"
git-tree-sha1 = "86c32a34b06c15b5ec8d4f694c2b91435253f209"
os = "macos"

    [[Zstd.download]]
    sha256 = "44b485a8b60851d143ed4a9b4683fd695b814e9644a70a8c31522d3fb6a1e928"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.4+0/Zstd.v1.5.4.aarch64-apple-darwin.tar.gz"
[[Zstd]]
arch = "aarch64"
git-tree-sha1 = "a1c557cc5b734ad1060f3d5fdd0ece65a608c323"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "909539a5acbf113b3ca02c61f887512fe023cc091e20abf8420a23ed4ed31b77"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.4+0/Zstd.v1.5.4.aarch64-linux-gnu.tar.gz"
[[Zstd]]
arch = "aarch64"
git-tree-sha1 = "bae1bb2ae1ad76da730d1d87a6f51f406ea6595e"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "b6be8f2c4456221eed9ce0ff2fb4d266df30ddc5bdb730021abf4c306e3fc196"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.4+0/Zstd.v1.5.4.aarch64-linux-musl.tar.gz"
[[Zstd]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5e61cc3dbdb02c184043cc611534a8021f5bef25"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "7fe1db2515e7e399c7ab76fbee8c630ffd0831a6c08a47314c5a6cc4b431c98a"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.4+0/Zstd.v1.5.4.armv6l-linux-gnueabihf.tar.gz"
[[Zstd]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b52a7b3912c30451beba773d854b8974ca8549b8"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "eeb0abb5eb6a672301ed1de4fd1f1d65c1f1cf9748c415f3c2d66a51bc230c75"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.4+0/Zstd.v1.5.4.armv6l-linux-musleabihf.tar.gz"
[[Zstd]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6bcebe1234c4362683e0bf4e5777693074ac65ac"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "82843f8cab9dea024f051a1907bee3927750b3924d9efa5372eaba8f853a733e"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.4+0/Zstd.v1.5.4.armv7l-linux-gnueabihf.tar.gz"
[[Zstd]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "08f327eadf5f6565f92ef0e201911d1273a89871"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "9cbc09b49386d9dce00450b87dcb8f597efdeed6d5ebb56286e3c253ff485cfc"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.4+0/Zstd.v1.5.4.armv7l-linux-musleabihf.tar.gz"
[[Zstd]]
arch = "i686"
git-tree-sha1 = "780cccee6d73be8a0cdccfd23fad05dab649e921"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "d8baf87065947270890dc751178d72852e55f08223ddab020a7751721f534b81"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.4+0/Zstd.v1.5.4.i686-linux-gnu.tar.gz"
[[Zstd]]
arch = "i686"
git-tree-sha1 = "997be54dee70d99159036eb364cbe1efbed330e5"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "5926802ee60a6225dc0d366407d0828c28340fb2d265345726674da350f1ffe1"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.4+0/Zstd.v1.5.4.i686-linux-musl.tar.gz"
[[Zstd]]
arch = "i686"
git-tree-sha1 = "f3c5b47e3978273847d3ef7564cfb7de85fa0283"
os = "windows"

    [[Zstd.download]]
    sha256 = "9269796e691bc786d58a8ab91c4e02afb1d90d7c2dfcdf55312681079630b1a3"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.4+0/Zstd.v1.5.4.i686-w64-mingw32.tar.gz"
[[Zstd]]
arch = "powerpc64le"
git-tree-sha1 = "7ae565c8e5571f19ff04d433b49bfd81a4f547ab"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "075492cc5ad1c53970de0f20578474248538f71237d58bd9a92d69c7b9551e3b"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.4+0/Zstd.v1.5.4.powerpc64le-linux-gnu.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "b82454601693d849c91e6b944795ef8bb370003a"
os = "macos"

    [[Zstd.download]]
    sha256 = "5b2ad040932412c4624d912a77deb94774f4c2397fc9ae66e7e8aeaec861e49e"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.4+0/Zstd.v1.5.4.x86_64-apple-darwin.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "1e31c68e8599ba2312bf4ae55651b8a5298ca7d5"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "9d078495fa2995542990b8c4eeb8d468dc389361988c62461a67fb294b43bc17"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.4+0/Zstd.v1.5.4.x86_64-linux-gnu.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "1784dd624362889a07d8e3eccd887ff511806798"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "5893fd7791eb3d2515d4f64ae03f56422b5301004ca6e5097381d910a513b500"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.4+0/Zstd.v1.5.4.x86_64-linux-musl.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "9335841415a7eae2e5c7714808e27b0144e1f9ca"
os = "freebsd"

    [[Zstd.download]]
    sha256 = "a715d1fc6690447520f22e6451fb803e1edd574fe87602ccf8391f32084c18ff"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.4+0/Zstd.v1.5.4.x86_64-unknown-freebsd.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "17025344af7bdfe8a7ac4e8887f0953f1dc50376"
os = "windows"

    [[Zstd.download]]
    sha256 = "5e881b71b167d7b6e1cb7d30d7a5dec9753ff017585a7e59394fa5e045b0fcd1"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.4+0/Zstd.v1.5.4.x86_64-w64-mingw32.tar.gz"
