[[Zstd]]
arch = "i686"
git-tree-sha1 = "95d4f06d3a6aedc7ac8ee48d2907b0cf8e39a25a"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "8db07fdfacb5f62cc09bdc8d82aa1d17f206e79f2945772e7f748d6710cceaf7"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.4+0/Zstd.v1.4.4.i686-linux-gnu.tar.gz"
[[Zstd]]
arch = "i686"
git-tree-sha1 = "5f6ec68819ff95e87d4136a750072af26b8e1c10"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "8a738c760d1d46d1d68dc9f0549deee3d869fff1e6158ba4acebb7dcae96a143"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.4+0/Zstd.v1.4.4.i686-linux-musl.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "7b96ae91dec5a65877199d5ba90a1628903238d2"
os = "macos"

    [[Zstd.download]]
    sha256 = "39fab2fd81c50329b2a5e7976fc30ab0f3ade037fe9371ae9d06103ab508790b"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.4+0/Zstd.v1.4.4.x86_64-apple-darwin14.tar.gz"
[[Zstd]]
arch = "powerpc64le"
git-tree-sha1 = "5b58ecb9eb2db7a579a897269823f62062dbb5ff"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "0028c0c5a73e1aac2b4ae7addd8714baa9a5afd4363feff7b2fb26bb49357bfd"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.4+0/Zstd.v1.4.4.powerpc64le-linux-gnu.tar.gz"
[[Zstd]]
arch = "aarch64"
git-tree-sha1 = "d159eb5face19f4fbfdc8129ac88f309b6b39f46"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "1eaa8e6d98ef17e094cc3bb44c567df17b41efbde77f7f62482876807c89a23c"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.4+0/Zstd.v1.4.4.aarch64-linux-gnu.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "b917d261f7f871b79c3db5380a5631a70e1fe80b"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "26eb0b88b63488d464d9897f11d2eb775faed2446f6ac3e582f87b11c533eb68"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.4+0/Zstd.v1.4.4.x86_64-linux-musl.tar.gz"
[[Zstd]]
arch = "aarch64"
git-tree-sha1 = "9fffae8179fe5be05c5a35e9dbf1a6e2e5a03fc7"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "6dedee7f363b8e5007cf3035668865cfccc94503b04ce41114105b4bd258ad00"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.4+0/Zstd.v1.4.4.aarch64-linux-musl.tar.gz"
[[Zstd]]
arch = "armv7l"
git-tree-sha1 = "fb07c68baa93df8008685daf21a8bb7fb6e6af90"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "5727449eec546efb2c856f311ab6a5250ebf67bdc182c47df0ede81ed60b3a96"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.4+0/Zstd.v1.4.4.arm-linux-musleabihf.tar.gz"
[[Zstd]]
arch = "i686"
git-tree-sha1 = "02b45f90de080548d02986a25840c99c78e19763"
os = "windows"

    [[Zstd.download]]
    sha256 = "e85bc21e220864f69baa53eed5fd6e3443003e16dd9c6c574d904887de033d14"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.4+0/Zstd.v1.4.4.i686-w64-mingw32.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "07bb74686344919bd384bc4fcb3a749c6df9100c"
os = "freebsd"

    [[Zstd.download]]
    sha256 = "3864a42d8339dcbae0674ce91cb9d5181b557bbb78d2d636ad28af4cc1ec30b1"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.4+0/Zstd.v1.4.4.x86_64-unknown-freebsd11.1.tar.gz"
[[Zstd]]
arch = "armv7l"
git-tree-sha1 = "80b1d78352711306c64b1af54c2f4be3ce948eb9"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "764fa412ced7b9bf904c66016602d818d446dde8de5cd67e30fe0c15bfc9603c"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.4+0/Zstd.v1.4.4.arm-linux-gnueabihf.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "ff9340a36d592615048d739e2fb8c10f2313334c"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "9efe77a7abf815a9eef21687c9ad222d89e91ebf0e8564b2910b30ca04a5c2ee"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.4+0/Zstd.v1.4.4.x86_64-linux-gnu.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "2c987d0ee933c3900ce3f148b81d7f7c9c704c56"
os = "windows"

    [[Zstd.download]]
    sha256 = "79867254e81a9b9c0878ee00a0605f06c8c6cdadf060a1d51f07de606971d763"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.4+0/Zstd.v1.4.4.x86_64-w64-mingw32.tar.gz"
