[[Zstd]]
arch = "aarch64"
git-tree-sha1 = "9a9f59eab237f7454fee1d6ab112a254032540b7"
os = "macos"

    [[Zstd.download]]
    sha256 = "764066f83bb76b355ea264f8dede8ec7fae27e31e0e8d6a927dd330394f1695a"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.5+0/Zstd.v1.5.5.aarch64-apple-darwin.tar.gz"
[[Zstd]]
arch = "aarch64"
git-tree-sha1 = "e2cb4528f4d901f0c98d964cb77b5af5719de2f5"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "6e50d069cf344d96fcb18d1f6779509ee1949c642cfa25a4ae72d9eef2d30f3d"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.5+0/Zstd.v1.5.5.aarch64-linux-gnu.tar.gz"
[[Zstd]]
arch = "aarch64"
git-tree-sha1 = "60353397075d85f109a5061b2a3f48bb2afd1e31"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "f50372e257fe26c44e017cad042489f7b14af185ddd4031bc7dc34f6d92e1e40"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.5+0/Zstd.v1.5.5.aarch64-linux-musl.tar.gz"
[[Zstd]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "85dbedb17f76c73f01410cd2711f57c5b792402d"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "24b2d177c3cabff6248acd7744c7ba41896f925abeab0b8afbcb7eb40d71c672"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.5+0/Zstd.v1.5.5.armv6l-linux-gnueabihf.tar.gz"
[[Zstd]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "66ac4f7fae7ba96ba2eed87f36a2d077918d5b6f"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "4f9913dfddfe615c18fbe47f2c8fcf75627a021ea83326217be0b99c6cf7a92e"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.5+0/Zstd.v1.5.5.armv6l-linux-musleabihf.tar.gz"
[[Zstd]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "56d02d05139a97578393061e7a20115176bcb839"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "8263621be231c6885872056a60ca9fc7b94f7a5eb037423af63f185ad478927d"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.5+0/Zstd.v1.5.5.armv7l-linux-gnueabihf.tar.gz"
[[Zstd]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "579453302e7c8aa613cc83e9a53b138bdd51f28b"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "fd8a879f41f5f2e655d40816d61509e9df4f17666f8ac7050f31c501d50ac780"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.5+0/Zstd.v1.5.5.armv7l-linux-musleabihf.tar.gz"
[[Zstd]]
arch = "i686"
git-tree-sha1 = "e2314283126b1798f4848d8e1815065b742671f2"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "9bb597c1a8c85c43f6deac3ed0efd693b601ab69ae452b8a1aa810b387ec0f05"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.5+0/Zstd.v1.5.5.i686-linux-gnu.tar.gz"
[[Zstd]]
arch = "i686"
git-tree-sha1 = "4d307c52b516d5459e4f9ce356340965dffa83f0"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "4801ab22468b431d99791837744c88b42a3e0e7f220956f33ac79b6123e28afd"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.5+0/Zstd.v1.5.5.i686-linux-musl.tar.gz"
[[Zstd]]
arch = "i686"
git-tree-sha1 = "fb2d96606d98e6a50c4eee0cef18d616e1e53fee"
os = "windows"

    [[Zstd.download]]
    sha256 = "3e6f68de7079165d64ae82eecb03c295d939340178d491bfc49661843ad11c9d"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.5+0/Zstd.v1.5.5.i686-w64-mingw32.tar.gz"
[[Zstd]]
arch = "powerpc64le"
git-tree-sha1 = "4c5695729defd2c9aa015e52c09e74e9363bdffd"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "5f3751ec7b0f7dd4afe263883cfd95d14f7d7f0b572dd49cbb98e47066c12705"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.5+0/Zstd.v1.5.5.powerpc64le-linux-gnu.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "ea3868d6f6440a23ac0ae1de3f0585928fe93ed3"
os = "macos"

    [[Zstd.download]]
    sha256 = "86c6fa7c4a091f1cd880d6e519ce9f92caff3478253ada5e62acdc8ba2e62745"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.5+0/Zstd.v1.5.5.x86_64-apple-darwin.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "00e677e85b66b11c69044b970c5a7d6d8c1534e9"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "12da888135a02be1d8171ca72a77d87df8b432c14f817a4c26e096e9c9bd7f70"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.5+0/Zstd.v1.5.5.x86_64-linux-gnu.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "b1d6e887ad436cacb51896e97bc682c8120dbba4"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "42df9a785a41055fe341597ed6402c3cc111dab9e4088a676132f9ef0cf30914"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.5+0/Zstd.v1.5.5.x86_64-linux-musl.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "098d9b17296637468a34069579cfabd075b773f5"
os = "freebsd"

    [[Zstd.download]]
    sha256 = "1555b8ef9fa4aacabd0de0a0391eba479e72ac8f650745a6832df745ae58f3df"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.5+0/Zstd.v1.5.5.x86_64-unknown-freebsd.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "17c7cf43a62bb170fc0e23af523744809703d7e2"
os = "windows"

    [[Zstd.download]]
    sha256 = "56ae3044d8a1d6e6ca330ef14ebb7b12150a66f1807197d818abdd2fc5cabf57"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.5+0/Zstd.v1.5.5.x86_64-w64-mingw32.tar.gz"
