[[Zstd]]
arch = "aarch64"
git-tree-sha1 = "1b3d05e1af5571e3dc596223ea161ce78ad30e1c"
os = "macos"

    [[Zstd.download]]
    sha256 = "3868ac7246a66f7422279d0ef90a58db493849d9c68e1bdee54d1e7057bbbc66"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.2+0/Zstd.v1.5.2.aarch64-apple-darwin.tar.gz"
[[Zstd]]
arch = "aarch64"
git-tree-sha1 = "a3ebaa5554c126e934d806c66b71a7497dfb9939"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "afee21df0a0c9c1206537bc40d57866bb17f78a3ee76f7fe6e1b90a25507eb57"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.2+0/Zstd.v1.5.2.aarch64-linux-gnu.tar.gz"
[[Zstd]]
arch = "aarch64"
git-tree-sha1 = "a902534dbdde44836016df8b06e0e67224caa156"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "134a9585e37a8ca312a9ddaaf4903c59aa7753ea8557a622cef499e01711666f"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.2+0/Zstd.v1.5.2.aarch64-linux-musl.tar.gz"
[[Zstd]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c2f5f0448e0e2348792f2f8bc42cf0b5d5a84966"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "d7ace99d2ec462899118082e971461701b057fb1ef1491bb90e235eda10a0d6a"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.2+0/Zstd.v1.5.2.armv6l-linux-gnueabihf.tar.gz"
[[Zstd]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6e681c4a38a90402b5310d324528bc08f642fca5"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "1e3605318d6279d33e7e619e6728bb0dde77cf465c4e71ff63d479b23c68bdfa"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.2+0/Zstd.v1.5.2.armv6l-linux-musleabihf.tar.gz"
[[Zstd]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a42d9fa4359e7077f6844f0df57c26c7d7e7f17d"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "540259f4541f37579e11a42536dfb1fd6355bdbebf055c36009a92fb4689e55e"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.2+0/Zstd.v1.5.2.armv7l-linux-gnueabihf.tar.gz"
[[Zstd]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c551f8e92a7785d844432eee94cd46ddf00f375e"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "1eb6d3eded8299220f3436c6d6a2b2262b3946e4381b1f309f7c195759f92e87"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.2+0/Zstd.v1.5.2.armv7l-linux-musleabihf.tar.gz"
[[Zstd]]
arch = "i686"
git-tree-sha1 = "357fbd99906b1a8d53994b45a4dea9df9a3ca488"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "f45518b0fc9cb6ca1ece842407de56400731f98d129017db97bf55d223e42b65"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.2+0/Zstd.v1.5.2.i686-linux-gnu.tar.gz"
[[Zstd]]
arch = "i686"
git-tree-sha1 = "8ef16c92396a519a0280e721d6c3883ff48c8b12"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "d8d631b5a75815ab95d2e870f927331132cb32dfc49b71b9503057dedb1643da"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.2+0/Zstd.v1.5.2.i686-linux-musl.tar.gz"
[[Zstd]]
arch = "i686"
git-tree-sha1 = "9e398a6e82582ba2c8a24dc1718800a4bdbfbe4d"
os = "windows"

    [[Zstd.download]]
    sha256 = "800713c203c4df6e77c8636deb6590fafad45eb120edd01f775271142b9d2e06"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.2+0/Zstd.v1.5.2.i686-w64-mingw32.tar.gz"
[[Zstd]]
arch = "powerpc64le"
git-tree-sha1 = "be0fca8fa7ead14df103b89a20f2586c74a9965b"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "52181b9d74f724db1e7843d92f2235d283dcae35bf1d81e08554eb67f074886c"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.2+0/Zstd.v1.5.2.powerpc64le-linux-gnu.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "2052a4bef64c555c78e154a23af351725ced4885"
os = "macos"

    [[Zstd.download]]
    sha256 = "5df470f75cc35a308d9f695a6f0836cad6f820e182280e0eaec4b5652673f5f3"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.2+0/Zstd.v1.5.2.x86_64-apple-darwin.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "d22cde7583df1d5f71160a8e4676955a66a91f33"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "9d0fff908e3e0273cc8360a3fb4696e4227bc5cd0dd10bd3a4c9d295b9e4e25e"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.2+0/Zstd.v1.5.2.x86_64-linux-gnu.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "bec91c0b47f1b0ef142ef2f74a263572e1139da1"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "22f4066ed6eedad8124a58be3a75a0f2cfb172087fd6fcbb612485620b9c5364"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.2+0/Zstd.v1.5.2.x86_64-linux-musl.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "c706882ca5ddadbe11dd4944026ed8db57e25b35"
os = "freebsd"

    [[Zstd.download]]
    sha256 = "94d2846163d7aadea88325a69dc3abe428b9f3a02ccdecfce3d1017d35b66184"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.2+0/Zstd.v1.5.2.x86_64-unknown-freebsd.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "3a34dec1472dcb90db22005558267071d9a8b913"
os = "windows"

    [[Zstd.download]]
    sha256 = "161fa231c22a11eb9e462034b692786ca89ef8bb22f9870710a086ff78b6f793"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.2+0/Zstd.v1.5.2.x86_64-w64-mingw32.tar.gz"
