[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "3e05e03b867bee479b9ad190b1a303d4a4e3fd1b"
os = "freebsd"

    [[Zstd.download]]
    sha256 = "790dae1e39457a67e8e597d799c12efa3f1a583d2648154d2d1f125004c507f2"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.5+0/Zstd.v1.4.5.x86_64-unknown-freebsd11.1.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "82c3723032478a243f80cd8970bb440de8393420"
os = "windows"

    [[Zstd.download]]
    sha256 = "2ae192ba8e0c559101e05a5047eace88d5f432e55225666fc99f7a3ec169343d"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.5+0/Zstd.v1.4.5.x86_64-w64-mingw32.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "fe796155110584ef8fadb469ba19b8a4910177b6"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "200a1b60d1d9507404a7f236bceb54c8bc3493a3b6b8539d14de1b3277bd9e38"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.5+0/Zstd.v1.4.5.x86_64-linux-gnu.tar.gz"
[[Zstd]]
arch = "armv7l"
git-tree-sha1 = "017f4c8a19841c6c32d2df12f36c188a5129ca37"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "14fcd0ad3cd824774c92661b56428263b36bb4ba1c7961904aa0c9aab9fab901"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.5+0/Zstd.v1.4.5.armv7l-linux-musleabihf.tar.gz"
[[Zstd]]
arch = "i686"
git-tree-sha1 = "34468cc77dabc7008b8dfbb513945672c7cf8855"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "463f8dac84e461fd423a9077a463b06fd5accc37c5520cfe8f5867e9ee9074a9"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.5+0/Zstd.v1.4.5.i686-linux-gnu.tar.gz"
[[Zstd]]
arch = "aarch64"
git-tree-sha1 = "3386e4fad283212afaaf8f6cbc1c4b95daa2e6b7"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "48590428bfad915765d7ff0aba93b5a8809fb7a503ab21048d5c9fe37e76eec2"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.5+0/Zstd.v1.4.5.aarch64-linux-musl.tar.gz"
[[Zstd]]
arch = "i686"
git-tree-sha1 = "588d9519e9674ec75871d2fdc25dcfec596fe7ac"
os = "windows"

    [[Zstd.download]]
    sha256 = "5e720f9575e21e4d0b962336d2ff479e8af728c835b1a54897b52eda9f80f37e"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.5+0/Zstd.v1.4.5.i686-w64-mingw32.tar.gz"
[[Zstd]]
arch = "aarch64"
git-tree-sha1 = "f770ac4977692530a8fae1bf81c9f1e723c263f5"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "509d47c60c439b839b4f01bdba8ccfde757142422a8e4652370f08745f3918ac"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.5+0/Zstd.v1.4.5.aarch64-linux-gnu.tar.gz"
[[Zstd]]
arch = "i686"
git-tree-sha1 = "383bd5c2d0cd0a0e8ee8f80ed681eb291a86d6fc"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "6a6c79366ec4bcbfce9f4941c1310428fbdd9721831b887baa45d3e588c64f49"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.5+0/Zstd.v1.4.5.i686-linux-musl.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "702bc4b7abb9f22922eb82d77740d78a489ed346"
libc = "musl"
os = "linux"

    [[Zstd.download]]
    sha256 = "8a45c5859694f6407e92785cc1b982a59cdf50fc0ef942ee6c4f6bd01ec7d5be"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.5+0/Zstd.v1.4.5.x86_64-linux-musl.tar.gz"
[[Zstd]]
arch = "powerpc64le"
git-tree-sha1 = "184a5639827b12a711c078632a98a75fac366e8e"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "c9232d3cc913b36bf21c44873682058841480a561894f789995301e929e75d74"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.5+0/Zstd.v1.4.5.powerpc64le-linux-gnu.tar.gz"
[[Zstd]]
arch = "x86_64"
git-tree-sha1 = "70d57db8fcf1997436540c9f876e3bacd36fb33b"
os = "macos"

    [[Zstd.download]]
    sha256 = "a75b8b8d7ed8e001c3b2c0d0190a40c566b93563b045157acd02ac825e1b561d"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.5+0/Zstd.v1.4.5.x86_64-apple-darwin14.tar.gz"
[[Zstd]]
arch = "armv7l"
git-tree-sha1 = "461d373413e3ce0ac2338fb221c132b97e752c51"
libc = "glibc"
os = "linux"

    [[Zstd.download]]
    sha256 = "b45c13208cb37fa8d2fa24995462f86694864eef0c537a8aff42fa5b12bd21fd"
    url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.4.5+0/Zstd.v1.4.5.armv7l-linux-gnueabihf.tar.gz"
